/// Flutter icons WeatherIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcons
///      fonts:
///       - asset: fonts/WeatherIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/widgets.dart';

class WeatherIcons {
  WeatherIcons._();

  static const _kFontFam = 'WeatherIcons';

  static const IconData attach_file = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData snow_heavy = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData fog_cloud = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData hail_inv = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData hail = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData cloud_flash = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData windy = const IconData(0xe806, fontFamily: _kFontFam);
}
